name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    needs:
      [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.3.0'

      - name: Install dependencies
        run: npm install
     

  cypress-run:
    runs-on: ubuntu-latest
    needs:
      [install, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.3.0'

      - name: Install dependencies
        run: npm install

  build:
    runs-on: ubuntu-latest
    needs:
      [install,cypress-run]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


